### ISSUE TITLE
Error even with examples in readme

### ISSUE THREAD

**Issue by josiekre** [transportfoundry/censusr#10]
I'm getting this error even when I run the examples in the readme file. Maybe a dependency messed things up? I don't know. 

```
Error in names(df) <- response[[1]] : 
  'names' attribute [1] must be the same length as the vector [0]
```

**Comment by josiekre** [comment]
So this error didn't happen when I pulled down the develop branch and ran the code manually. Only when I was calling library from a cran install.

Will come back to this...

**Comment by josiekre** [comment]
And now it didn't happen. So I'm closing this. Not sure what my issue was. Maybe the API was down? Who knows.

**Comment by gregmacfarlane** [comment]
Well, I'm glad we got that sorted at least!
