### ISSUE TITLE
On CRAN, 'knitr' is a suggested package. Why?

### ISSUE THREAD

**Issue by josiekre** [transportfoundry/censusr#11]
@gregmacfarlane I'm wondering if anything will break if I remove knitr from the list of suggested packages. Thoughts?

**Comment by gregmacfarlane** [comment]
Hadley [recommends](http://r-pkgs.had.co.nz/vignettes.html) that you suggest `knitr` when the package vignette is built with knitr. In fact, `devtools::use_vignette()` added this to `DESCRIPTION` automatically.

I'd leave it there.
