### ISSUE TITLE
Multiple geographies

### ISSUE THREAD

**Issue by gregmacfarlane** [transportfoundry/censusr#2]
There should be a way to submit a `geoid*` to get all of the sub-geos in that geoid. You've already done this internally (in a really hacky way). Put it up.

**Comment by josiekre** [comment]
I'm adding a variable `allgeos` that can be c(NULL, "co", "tr", "bg", "bl"). If anything other than NULL, it will append the string to the url as x=*. Our input list to `call_census_api` is getting pretty long. Do you usually specify the `variable = something` when calling this function, or do you rely on the order and leave them un-named?

**Comment by gregmacfarlane** [comment]
I usually name them. But would it be possible to make it opaque to the user? That is, if they sent in

```
...geoid = "37083*", level = "tr"...
```

it could return all tracts in the county? We would `grepl("*", geoid)` and send them to a different url constructor. If they provide `level` without a `*`, we could just warn that we're ignoring it.

**Comment by josiekre** [comment]
That's a different approach than I was taking but I like it. I was just going to have this

```
...geoid = c("37083"), allgeos = "bl"...
```

return all blocks in the county 37083, aggregated at the block level. However,

```
...geoid = c("37083")...
```

would return data aggregated at the county level. `allgeos` assumes `NULL` in this case. What do you think of this?

**Comment by gregmacfarlane** [comment]
That is even easier. I like it.
