### ISSUE TITLE
Add support for geocoding address to census geography

### ISSUE THREAD

**Issue by josiekre** [transportfoundry/censusr#22]
What do you think of adding support here for the Census geocoder to grab geoids for a particular address? It's technically maintained by a different group within the Census, but I have a need for it. I can add it here, or create it elsewhere. What do you think @gregmacfarlane?

**Comment by gregmacfarlane** [comment]
I think that would definitely be cool, and I think it fits within this scope.

**Comment by josiekre** [comment]
Do I branch off of master with something like "feature-census-geolocator"? I don't see any feature branches in the repo history.

**Comment by gregmacfarlane** [comment]
Closed as of #28
