### ISSUE TITLE
One function to rule them all

### ISSUE THREAD

**Issue by gregmacfarlane** [transportfoundry/censusr#3]
Maintaining the code will be easier if there's only one function that needs maintaining. Consider merging the ACS and SF1 function.

**Comment by josiekre** [comment]
This would take care of [Issue #4](https://github.com/gregmacfarlane/censusr/issues/4).

**Comment by gregmacfarlane** [comment]
Yeah. I also think having a function option to direct to the right dataset is better.

**Comment by josiekre** [comment]
I believe we can close this issue now too.

**Comment by gregmacfarlane** [comment]
The issues get marked as closed when we release them into `master`. But it's really not a problem for you to close them.
