### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by gregmacfarlane** [transportfoundry/censusr#5]
Right now if the user asks for a variable that's not there or for an unsupported geography, everything just kind of breaks. It would be good to handle these better.

**Comment by josiekre** [comment]
I committed a few yesterday that starts getting at this (https://github.com/gregmacfarlane/censusr/commit/1f6d0e71dffc3d4da8292ea7aba8f11bbf97b520 and https://github.com/gregmacfarlane/censusr/commit/a41d6c9dd8cdc185b6af0fc973c235fc0e28cfda).

**Comment by josiekre** [comment]
I think I'll close this. We can create new issues that are more specific to future error handling.
