### ISSUE TITLE
Put names on the returned table.

### ISSUE THREAD

**Issue by gregmacfarlane** [transportfoundry/censusr#7]
Right now I do something like this:

``` r
d <- call_census_api(...)
names(d) <- names_vector
d %>%
  # cleaning #
```

Better?

``` r
call_census_api(..., names = names_vector) %>%
  # cleaning #
```

**Comment by josiekre** [comment]
What kind of names are you meaning? Right now it returns the cryptic code as the name of variables, right? The long names that come from the API are very un-R like with spaces and such.

I usually rename the cryptic codes right away, so I suppose passing in a names_vector would be nice. But we need to worry about order.

**Comment by gregmacfarlane** [comment]
The function returns the table in the same order as the variables we requested, right? So I'm thinking (with totally made-up variables)

``` r
call_census_api(
  ..., 
  variables = c("B05109E_01", "B05109M_01"), 
  names = c("pop_est", "pop_moe")
)
```

is marginally easier than getting the data and renaming it in two different steps. If the order is changing, I've got bigger issues...

**Comment by josiekre** [comment]
Looks great to me. Let's make sure that w/o `names` specified, it defaults to `variables`. So something like:

``` r
call_census_api <- function(..., variables, names = variables, ... )
```

I do think you're right in that the order stays the same. But it's worth testing.
